name: "Generate SBOM for the repository"
on:
  push:
    branches: [main]
  pull_request:
    types: [opened, synchronize, reopened]
jobs:
  generate-sbom:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@master
    - uses: anchore/sbom-action@v0
      with:
        path: ./
        artifact-name: sbom.cdx.json
        format: cyclonedx-json
